# Store video codes for each sign language word
SIGN_VIDEOS = {
    "hello": "ns3nvo9mpj",
    "goodbye": "1jqvdn4kow",
    "thank_you": "pdmmfefdff",
    "please": "nti5jzikz6",
    "sorry": "thdxo8twup",
    "yes": "pqgak01sun",
    "no": "0vycdillx8",
    "maybe": "byblzeix7t",
    "one": "mxwf7kphpz",
    "two": "9kxdliygm5",
    "three": "vqnue9bgxe",
    "four": "kxamml6ogh",
    "five": "hf91kna1ai",
    "six": "ljij2w0mxs",
    "seven": "ovak0dmbuq",
    "eight": "8zew4o1lrb",
    "nine": "wmywtcyb4j",
    "ten": "jnpdtpmo9l",
    "mother": "xhumgambd0",
    "father": "wg99m7o6om",
    "brother": "shmgffyrlm",
    "sister": "cj5wxieev1",
    "friend": "y0copmlysx",
    "red": "vhxdhxljbc",
    "blue": "fxqwepxm7j",
    "green": "k0p9cpqpzy",
    "yellow": "yxvqepltwd",
    "white": "zspnng9zo5",
    "black": "vkokqksf6v",
    "happy": "upqz5ebm4n",
    "sad": "idzih4ih1g",
    "angry": "0twdyiqkgd",
    "tired": "pjvijjq1zx",
    "love": "tej0m2zew3",
    "what": "7ou1bjsait",
    "where": "sibioxossa",
    "who": "oco0msxi7x",
    "when": "awxr8ofuol",
    "how": "8ksemb7sgk",
    "eat": "kpyrqtjqsr",
    "drink": "bhmijdp3cz",
    "water": "zx36azvpcf",
    "more": "qyegtcfc7a",
    "finished": "24ghxkesl4",
    "help": "shpdlzz5rp",
    "stop": "h7gy7mrrjr",
    "wait": "oxrmaeaxsl",
    "understand": "ibnpmkklcq"
}

def get_video_code(sign_name):
    """Returns the video code for the given sign name"""
    return SIGN_VIDEOS.get(sign_name.lower(), None)