# Generated by Django 6.0.3 on 2026-03-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otpcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset')], max_length=20),
        ),
    ]
